channels:
  - conda-forge
  - bioconda
  - r
  - defaults
  - anaconda
dependencies:
   - openms=2.3.0
   - msgf_plus=2017.07.21
   - prokka=1.13
   - quast=5.0.0
   - multiqc=1.6
   - spades=3.12.0
   - trim-galore=0.5.0
   - fastqc=0.11.6
